[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm ci",
  "pip install -r scripts/requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
